services:
  lifesyncdb:
    image: postgres

  rabbitmq:
    image: rabbitmq:management

  mailhog:
    image: mailhog/mailhog

  taskmanagerapi:
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build:
      context: .
      dockerfile: Services/TaskManager/TaskManager.API/Dockerfile

  nutritionapi:
    image: ${DOCKER_REGISTRY-}nutritionapi
    build:
      context: .
      dockerfile: Services/Nutrition/Nutrition.API/Dockerfile

  financialapi:
    image: ${DOCKER_REGISTRY-}financialapi
    build:
      context: .
      dockerfile: Services/Financial/Financial.API/Dockerfile

  usersapi:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Services/Users/Users.API/Dockerfile

  emailsenderapi:
    image: ${DOCKER_REGISTRY-}emailsenderapi
    build:
      context: .
      dockerfile: Services/Notification/Notification.API/Dockerfile

  gymapi:
    image: ${DOCKER_REGISTRY-}gymapi
    build:
      context: .
      dockerfile: Services/Gym/Gym.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpgateway
    build:
      context: .
      dockerfile: Services/ApiGateways/YarpApiGateway/Dockerfile

volumes:
  postgres_lifesync:
  pgadmin_data:
