<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.8" />
    <PackageReference Include="Syncfusion.Blazor.Buttons" Version="33.2.10" />
    <PackageReference Include="Syncfusion.Blazor.Cards" Version="33.2.10" />
    <PackageReference Include="Syncfusion.Blazor.DropDowns" Version="33.2.10" />
    <PackageReference Include="Syncfusion.Blazor.Grid" Version="33.2.10" />
    <PackageReference Include="Syncfusion.Blazor.Inputs" Version="33.2.10" />
    <PackageReference Include="Syncfusion.Blazor.Navigations" Version="33.2.10" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="33.2.10" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\" />
  </ItemGroup>

</Project>
